Vagrant.configure("2") do |config|

config.vm.define "ansible" do |ansible|
  ansible.vm.box = "generic/debian12"
  ansible.vm.network "public_network"
  ansible.vm.network "private_network", ip: "192.168.50.41", virtualbox__intnet: "ansible_lab"
  ansible.vm.hostname = "ansible"
  ansible.vm.synced_folder "./ansible_data", "/vagrant_data"
  ansible.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "2048"]
    vb.customize ["modifyvm", :id, "--cpus", "2"]
	vb.name = "ansible"
    end
  ansible.vm.provision "shell", inline: <<-SHELL
    apt update
    apt install -y git ansible
  SHELL
  end
config.vm.define "ubuntu" do |ubuntu|
  ubuntu.vm.box = "generic/ubuntu2304"
  ubuntu.vm.network "public_network"
  ubuntu.vm.network "private_network", ip: "192.168.50.43", virtualbox__intnet: "ansible_lab"
  ubuntu.vm.hostname = "ubuntu"
  ubuntu.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "2048"]
    vb.customize ["modifyvm", :id, "--cpus", "2"]
	vb.name = "Ubuntu"
    end
  ubuntu.vm.provision "shell", inline: <<-SHELL
    apt update
    apt install mc
    apt-add-repository ppa:fish-shell/release-3
    apt update && sudo apt-get upgrade
    apt install fish
    chsh -s /usr/local/bin/fish
    echo "/usr/local/bin/fish" | sudo tee -a /etc/shells
    chsh -s /usr/local/bin/fish
  SHELL
  end
config.vm.define "debian" do |debian|
  debian.vm.box = "generic/debian12"
  debian.vm.network "public_network"
  debian.vm.network "private_network", ip: "192.168.50.42", virtualbox__intnet: "ansible_lab"
  debian.vm.hostname = "debian"
  debian.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "2048"]
    vb.customize ["modifyvm", :id, "--cpus", "2"]
	vb.name = "debian"
    end
  debian.vm.provision "shell", inline: <<-SHELL
    apt update
    apt install mc
    apt-add-repository ppa:fish-shell/release-3
    apt update && sudo apt-get upgrade
    apt install fish
    chsh -s /usr/local/bin/fish
    echo "/usr/local/bin/fish" | sudo tee -a /etc/shells
    chsh -s /usr/local/bin/fish
  SHELL
  end
config.vm.define "alma" do |alma|
  alma.vm.box = "generic/alma9"
  alma.vm.network "public_network"
  alma.vm.network "private_network", ip: "192.168.50.44", virtualbox__intnet: "ansible_lab"
  alma.vm.hostname = "almalinux"
  alma.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "2048"]
    vb.customize ["modifyvm", :id, "--cpus", "2"]
	vb.name = "AlmaLinux"
    end
  alma.vm.provision "shell", inline: <<-SHELL
    yum install mc
    yum install fish
  SHELL
  end
end